name: Envi CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  go-backend-workflow:
    uses: Clarilab/workflows/.github/workflows/go-backend.yaml@main
    with:
      work_dir: .