# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feature/add-filewatcher" ]
  workflow_dispatch:
  
jobs:
  filewatch:
    name: Filewatch CI
    runs-on: ubuntu-latest
    env: 
      WORKDIR: ./filewatch
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">=1.20.6"

    - name: Vet
      working-directory: ${{ env.WORKDIR }}
      run: go vet ./...

    - name: Test
      working-directory: ${{ env.WORKDIR }}
      run: go test -short -v ./...

    - name: Vuln
      id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
        work-dir: ${{ env.WORKDIR }}
        check-latest: true

  envi:
    name: Envi CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ">=1.20.6"

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -short -v ./...

    - name: Vuln
      id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
        check-latest: true